name: Deploy website on push

on:
  push:
    branches:
      - oma

jobs:
  web-deploy:
    name: Deploy via SFTP
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync via SFTP using lftp
      env:
        HOST: ${{ secrets.ftp_server }}
        USER: ${{ secrets.ftp_username }}
        PASS: ${{ secrets.ftp_password }}
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -c "
        set sftp:auto-confirm yes;
        open -u $USER,$PASS sftp://$HOST:22;
        mirror -R --delete --verbose ./ ./www/;
        "
